name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Fetch history
      run: git fetch --prune --unshallow
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
           9.0.x
    - name: Restore dependencies
      run: |
        dotnet restore src/TiaProjectBrowser.slnx
    
    - name: Build
      run: |
        dotnet build -c Release src/TiaProjectBrowser.slnx
    - uses: actions/upload-artifact@v4
      with:
        path: src/S7CommPlusDriver/bin/Release/*.*